### PR TITLE
Fix formatting with `$` and `<>`

### PR DESCRIPTION
**Pull request by etiennebacher**
Reported in https://github.com/pola-rs/r-polars/issues/605

* escape the `$` in man pages otherwise mkdocs thinks it is a latex equation and doesn't escape symbols between two `$`
* add basic code and equation in snapshot test
* fix wrong replacement for some UTF8 (see [the value for 8288](https://www.w3schools.com/charsets/ref_utf_punctuation.asp))

Not very happy because the output in some docs moves from `$` to `\$`.

@vincentarelbundock this fixes it for `polars` but it would be great if you could check it this has undesirable side effects on your packages

### CODE REVIEW

**Comment by etiennebacher** [comment]
I'm merging this, it's always possible to pin `altdoc` to the previous commit

**Comment by vincentarelbundock** [comment]
Hmm, maybe this is fine? I think the recommended math in .Rd file is ` \eqn{Beta(\alpha c_{i,j} +\beta, c_{i,j}+\beta)}`, and I don't see a Roxygen recommendation to use $$ in a quick googling.

**Comment by etiennebacher** [comment]
I don't understand if you're ok with this change or not. Just to clarify, this modifies the .qmd file, not the .Rd one

**Comment by vincentarelbundock** [comment]
I thought it was OK, but I just tried it, and it is *not*:

```r
processing file: marginal_means.qmd
Quitting from lines 508-578 [unnamed-chunk-1] (marginal_means.qmd)
Error in `parse()`:
! <text>:7:4: unexpected '\\'
6: dat <- mtcars
7: dat\
      ^
```

The corresponding line in the documentation is just a standard use of retrieving a column with the `$` operator in code:

```r
\examples{
library(marginaleffects)

# simple marginal means for each level of `cyl`
dat <- mtcars
dat$carb <- factor(dat$carb)
dat$cyl <- factor(dat$cyl)
dat$am <- as.logical(dat$am)
mod <- lm(mpg ~ carb + cyl + am, dat)
```

So it looks like you are also substituting in the examples.

**Comment by etiennebacher** [comment]
Thanks for the example, I'll fix this

**Pull request merged**
