### PR TITLE
Create GHA workflow for altdoc

### LINKED ISSUE #66: Automatically create a GHA workflow
A bit more long term but when `altdoc` is more robust and #47 is solved, it would be nice to have a function to make a GHA workflow for `altdoc`, sort of `usethis::use_github_action("pkgdown")`

### PR DESCRIPTION
**Pull request by etiennebacher**
Close #66 

Very much WIP, just the skeleton for now

TODO:
- [x] use `r2u`
- [x] check if installing the package `quarto` is enough or if we need to setup Quarto: https://github.com/quarto-dev/quarto-actions/tree/main/setup

### CODE REVIEW

**Comment by vincentarelbundock** [comment]
This assumes we want to create an all new website every time, with no customization at all?

**Comment by vincentarelbundock** [comment]
How about setup_workflow()?

**Comment by etiennebacher** [comment]
Quarto installation fails because `sudo: command not found`. @vincentarelbundock do you think it's because we use a rocker container?

**Comment by vincentarelbundock** [comment]
No idea, which is why I use the script linked above ;)

**Comment by etiennebacher** [comment]
https://github.com/quarto-dev/quarto-actions/issues/12

> There are cases where install-quarto action can't be used (like in docker containers runners).

**Comment by etiennebacher** [comment]
The CI went through, need to see how it goes after we merge this. Need to update function name, docs, CI template first

**Comment by vincentarelbundock** [comment]
this is cool

**Comment by vincentarelbundock** [comment]
Out of curiosity, what is the benefits of pushing to a separate branch vs. just loading it directly from `docs/` in `main`?

**Comment by etiennebacher** [comment]
> this is cool

yes but it still doesn't work because git is not installed / badly configured in the container. I'm exploring now

> Out of curiosity, what is the benefits of pushing to a separate branch vs. just loading it directly from docs/ in main?

After a you merge a PR / push some commits, you don't need to pull again to import locally the changes in the `docs` folder

**Pull request merged**
