### PR TITLE
Add link to source code in man pages

### LINKED ISSUE #86: Add link to source file in man page
Only works for `roxygen2` docs so should be optional.

Extract link from parsed Rd:
```r
get_r_source = function(src) {
  parsed = as.character(src)
  contains_source = grep("% Please edit documentation in", parsed)
  r_source = sub(
    "% Please edit documentation in ", "",
    parsed[contains_source]
  )
  return(
    list(
      file = r_source,
      link = paste0("https://github.com/pola-rs/r-polars/tree/main/", r_source)
    )
  )
}
```

Example in `polars`:

image

Note: one tricky thing could be to determine if the branch is `main` or `master`

### PR DESCRIPTION
**Pull request by etiennebacher**
Close #86 

For example, here's the link in the docs of `setup_github_actions()`: https://github.com/etiennebacher/altdoc/blob/main/R/setup_github_actions.R#L17

### CODE REVIEW

**Comment by vincentarelbundock** [comment]
What kinds of assumptions does this make? For example, will it work here, where the package is in a subdirectory? Will the links be 404 Not Found?

https://github.com/markvanderloo/tinytest

In general, I think that features that make strong assumptions should be turned off by default with an argument (like you convinced me to do with freeze).

**Comment by etiennebacher** [comment]
> For example, will it work here, where the package is in a subdirectory? Will the links be 404 Not Found?

Yes I suppose they will if we don't handle this type of case. Notice that the CI will fail anyway in this kind of repo because we do `install.packages(".")` and this would fail at the root of the repo.

**Comment by vincentarelbundock** [comment]
> Notice that the CI will fail anyway in this kind of repo because we do `install.packages(".")` and this would fail at the root of the repo.

Right, but that's less critical because it's not a "default" option.

**Comment by etiennebacher** [comment]
> In general, I think that features that make strong assumptions should be turned off by default with an argument (like you convinced me to do with freeze).

Are you okay with including an argument `link_to_source = FALSE` in `render_docs()`? I don't see an alternative for this

**Comment by vincentarelbundock** [comment]
Yes, that sounds great. I ce off as too negative: this is a very nice feature and the argument default you propose is perfect.

**Comment by etiennebacher** [comment]
> I ce off as too negative

Not at all, it's good that you reminded me of this kind of corner case. I found a way to check whether the link to source leads to 404. That way, if we get a wrong URL for packages like `tinytest` then the links won't be included in the docs

**Comment by etiennebacher** [comment]
Several issues: 

* `getSrcLocation()` requires the package to be loaded. Not a problem for CI but can generate an error locally
* deal with names like `"WDI-package"`

**Comment by etiennebacher** [comment]
Tried for a couple of packages and it works fine. I'll merge later unless you want to add some comments here @vincentarelbundock

**Pull request merged**
