### PR TITLE
Simplify vignettes conversion 2

### LINKED ISSUE #43: Simplify vignettes
I'm wondering if we could simplify the vignette code by:

1. Copying the whole content of `vignettes/` over to `docs/articles/`. This would preserve relative links and allow us to remove the figures modification code, which relies on tricky regexes. https://github.com/etiennebacher/altdoc/blob/main/R/vignettes.R#L39
2. Use the `output_format` argument in `rmarkdown::render` to obviate the need to hack the YAML: https://github.com/etiennebacher/altdoc/blob/main/R/vignettes.R#L54

### PR DESCRIPTION
**Pull request by rempsyc**
Closes #43, continuation of #48.

### CODE REVIEW

**Comment by rempsyc** [comment]
Here’s a summary of my testing regarding the logo issue:
1.	No logo added with `altdoc`, because the README does not include the logo.
2.	Logo works with `datawizard` and `countrycode`, because their README include an internal reference in the title (like ``)
3.	Logo doesn’t work with `lavaanExtra`, because the README does not include an explicit reference to the logo. This suggests that the logo is actually automatically added by `pkgdown`.
4.	Logo doesn’t work with `WDI`, but it also doesn’t work with `pkgdown`. Maybe the site hasn’t been updated  for a while (seems like it was some 3 years ago).

We have two options here:
1. Assume responsibility of the user to add an internal reference to the logo explicitly, or;
2. Attempt to mimic pkgdown to add it automatically.

I tested with the current CRAN version, and this behaviour is the same. Therefore, the logo is not actually a downgrade, so we could go with option 1 and merge these changes as is.

@vincentarelbundock here is code for you to test. From the `countrycode` or `WDI` root working directory, use the following command:

```r
library(altdoc)
use_docsify()
```

To try the alternative renderers, simply follow with:
```r
use_docute()
use_mkdocs() # Assumes you have mkdocs already installed
```

**Comment by rempsyc** [comment]
Ok, I fixed the issue of images generated through code not rendering (tested on datawizard only for now). Unfortunately, I had to rely on regex replacements even though the images live within docs. As explained by the following comment:

> However, docute and docsify need the paths in the .md files to
> start with "articles/figures/" so I need to add "articles/"
> just before "figures/" in the img paths, *after* compilation.
> 

So the images won’t show if they are within the default path of e.g., `"articles/standardize_data_files/figure-gfm/unnamed-chunk-16-1.png"`, so they need to be replaced with e.g., `"articles/figures/unnamed-chunk-16-1.png"`.

**Comment by vincentarelbundock** [comment]
@rempsyc thanks a lot for your work on this!!

Just to clarify: Do you expect any backward incompatibility at all with this PR?

**Comment by vincentarelbundock** [comment]
```r
library(altdoc)
update_docs()
Error in .reformat_md(docs_file, first) : 
  argument "first" is missing, with no default
```

**Comment by rempsyc** [comment]
Yes I expect backward compatibility, thanks for pointing this problem out! Will try to resolve it next.

**Review by vincentarelbundock — APPROVED** [review]

**Comment by rempsyc** [comment]
Ok I didn't get the error you mentioned when when testing on `altdoc` itself, which also has no `articles` folder. But I realize this is because I was only testing `use_docsify()`, not `update_docs()`.

However, I do get this error with `update_docs()` and `datawizard` actually. However, when I ran it the second time, it worked, so seems inconsistent, but I can replicate this pattern consistently (always work on second try). This is interesting that the problem is with `update_docs()` since I did not bring changes to this function or underlying functions, I think.

I’m also experiencing a new weird issue, where when I tested support for code-generated images earlier, it was working, and now, it doesn't seem to be anymore. Seems like the issue is that rendering the vignettes with `rmarkdown::render()` does not create the corresponding "articles/standardize_data_files/figure-gfm/unnamed-chunk-16-1.png" subfolders. Even regressing my changes these figures just don’t appear in articles, so even though I try to move them, there is nothing to move. I am a bit confused by this, so since this does not address this issue directly (i.e., it’s an extra) and that this issue has been merged, I think I'll focus on the quarto conversion PR instead.

**Comment by rempsyc** [comment]
(Note to myself about the code-generated images problem)

---

The issue seems specific to the `datawizard`'s `standardize_data.md` vignette, which not only does not render the images, but does not render code chunks at all (whereas other vignettes render code correctly).

I run the following base code from the root `datawizard` repo:

```r
path = "."
vignettes_path <- fs::path_abs("vignettes", start = path)
articles_path <- paste0(altdoc:::.doc_path(path = path), "/articles")
vignettes <- list.files(vignettes_path, pattern = ".Rmd$")

i <- 2
j <- vignettes[i]

origin <- paste0(vignettes_path, "/", j)
destination <- paste0(articles_path, "/", j)
output_file <- paste0(substr(j, 1, nchar(j)-4), ".md")

rmarkdown::render(
  origin,
  output_dir = articles_path,
  output_file = output_file,
  output_format = "github_document",
  quiet = TRUE,
  envir = new.env()
)
```

And the resulting md (and html file) does not render chunks at all:

no output md

**Comment by vincentarelbundock** [comment]
Maybe just leave an open issue and move on? This sounds a bit niche and we won't convert the datawizard anyway, so let's not waste too much time on this. It would be nice to fix, of course, but lower priority it works elsewhere.

**Pull request merged**
