### PR TITLE
Set `parallel = FALSE` by default in GHA

### LINKED ISSUE #251: `parallel = FALSE` by default in github workflow
Otherwise everyone needs to install `future`, which may not be a dependency of the particular project.

### PR DESCRIPTION
**Pull request by etiennebacher**
Close #251

### CODE REVIEW

**Comment by vincentarelbundock** [comment]
Nice, thanks!

I ran into this while making my latest package site public. Haven't posted to the socials yet because there are a couple more bugs to fix, but I'm pretty excited about it.

Mundane task: Data frame -> Table. But suuuuper easy to use and incredibly flexible. Plus, 0-dependency. Let me know if you try it: https://vincentarelbundock.github.io/tinytable/

tinytable_gallery

**Comment by etiennebacher** [comment]
I saw your repo like 5min after you made it public ^^ Looks very nice, I'm not sure I have the willingness to learn another package to make tables, but if you made it you must have nice usecase for it. I'll definitely take a look :)

**Comment by vincentarelbundock** [comment]
Haha, yeah. The beauty of it is that there's basically nothing to learn. I just couldn't deal with the 100 functions in other table packages (and 60+ dependencies), so I designed my own.

There's basically two functions in the whole package: `tt()` and `style_tt()`.

```r
library(tinytable)
x <- mtcars[1:4, 1:4]

tt(x)

tt(x) |> style_tt(color = "orange")
```

But yeah, I totally get that very few people want to learn a new package.

**Comment by etiennebacher** [comment]
> There's basically two functions in the whole package: tt() and style_tt().

Btw I think you forgot to export `style_tt()`

**Comment by vincentarelbundock** [comment]
haha, fixed

**Comment by etiennebacher** [comment]
I always find the 0-dep label nice to have, and at the same time I constantly use the tidyverse pkgs in my work so I'm never really the target for this. I've probably not been in the domain for long enough to truly enjoy no-dep pkgs ^^ 

> The beauty of it is that there's basically nothing to learn

Just wait for the 100+ feature requests 😄 You should start making a package / website called "arelbundock-verse" with `marginaleffects` + `modelsummary` + `tinytable` + `tinysnapshot` + `countrycode`, that's a nice collection

**Comment by vincentarelbundock** [comment]
For me, it's mostly that I don't use the tidyverse on a day to day basis, so it's annoying when I do a `renv` and have to load 65 extra packages just to draw tables. But I've also been bitten by old code breakage many times, and I hate it. 

I do understand that it's not a selling point for many. Hopefully the simple interface will be enough of a selling point for those people.

**Pull request merged**
