### PR TITLE
Simplify vignettes conversion

### PR DESCRIPTION
**Pull request by etiennebacher**
Following discussion in #47.

I quickly tested on `datawizard` and it looked good but more testing required (the only reason it passes CI is because I have very few tests for vignette conversion).

@vincentarelbundock I was just curious to see if adding `output_format = "github_document"` would work. I'm not sure I'll finish this PR but I just put this here if you want to use it later

### CODE REVIEW

**Comment by vincentarelbundock** [comment]
Very nice. Another benefit of this simplification is that it'll be trivial to support Quarto vignettes: just swap `rmarkdown::render` by `quarto::render`

**Comment by rempsyc** [comment]
Step 7 (continued from #46): Vignettes don't appear per default on the rendered website, but the NEWS file explains that:
> Vignettes are no longer automatically added to the file that defines the structure
  of the website. Developers must now manually update this structure and the order
  of their articles.

For this, we need an example to understand where vignettes should be moved to. The `altdoc` website itself does not seem to use vignettes and the package does not have a corresponding folder. The `conductor` website however, has several example vignettes (e.g., `demo`) rendered on the website, so these act as a useful examples. That said, the vignettes are not located in a vignette folder within the repository, but in a `docs/articles` subfolder.

With `datawizard` and the following PR branch, I use:

``` r
library(altdoc)
use_docute()
```

And I can see that the vignettes have been correctly rendered in `docs/articles`, but that they still do not appear on the rendered website. Above we come back to the warning relating "to the file that defines the structure of the website", and so we must identify where this file lives [it would be helpful to specify the name of the file or where to find it or add more information anyhow]. For `pkgdown`, that file would usually be `_pkgdown.yaml`, so we have to find an equivalent. I cannot find this file for `datawizard`. So if we look at the `conductor` demo vignette to enlighten us, well, I cannot find it either.

Could it simply be `_sidebar.md`?

**Comment by rempsyc** [comment]
In `datawizard`, I added a file similarly called `_sidebar.md` and specified the correct vignette names, but after re-rendering the site, they still do not appear at the right location.

I checked in the conductor repo for `_sidebar.md` and `_sidebar` but I am only getting that file, so I don’t know how or where it is referenced so that it is picked up by rendering the website.

**Comment by rempsyc** [comment]
(as a side note, I am not able to correctly install `mkdocs` on Windows 10, see: mkdocs/mkdocs#3427. Are you guys on Mac?)

**Comment by rempsyc** [comment]
The content of my `_sidebar.md` is:

```md
* [Home](/)

* [Reference](reference.md)

* Articles
  * [Coming from 'tidyverse'](articles/tidyverse_translation.md)
  * [A quick summary of selection syntax in `{datawizard}`](articles/selection_syntax.md)
  * [Data Standardization](articles/standardize_data.md)

* [Changelog](NEWS.md)
* [License](LICENSE.md)

```

Not sure if the problem is the way I've specified this site structure.

**Comment by rempsyc** [comment]
Ok, `_sidebar.md` is only for `use_docsify()` and works as expected, and is created when running the command. We actually get warned about this (indirectly) when running `use_docsify()`:

```r 
ℹ The folder vignettes was not modified.
! Don't forget to check that vignettes are correctly included in C:/github/datawizard/docs/_sidebar.md.
```

Whereas, `use_docute()` warns you similarly:

```r 
ℹ The folder vignettes was not modified.
! Don't forget to check that vignettes are correctly included in C:/github/datawizard/docs/index.html.
```

And also create the corresponding file automatically, but this time it is an html file called `index.html`.

So the conclusion is that **_the name of the file defining the structure of the website differs based on the selected site builder_**. 

This makes it difficult to easily change between one format or the other if we have to bring manual changes to this file to include vignettes, hum... but perhaps it is unavoidable at this stage (yet again perhaps this could be a future feature request).

**Comment by rempsyc** [comment]
After a careful comparison of vignette rendering between `use_docsify()` and `pkgdown` for `datawizard`, I can confirm that everything seems to work as expected.

However, one difference is internal and external links. In pkgdown, things like:
```r
library(dplyr)
```
Actually links externally to `https://rdrr.io/r/base/library.html` for `library` and `https://dplyr.tidyverse.org/` for `dplyr`. And things like:
```r
data_filter() 
```
Actually links internally to `reference/data_match.html`. However, this is a rather minor element (perhaps even a feature).

**Comment by rempsyc** [comment]
One issue is the inclusion of images, where for example the `standardize_data.md` vignette refers to the following image:

```
<img src="C:/github/datawizard/docs/articles/standardize_data_files/figure-gfm/unnamed-chunk-13-1.png" 
style="display: block; margin: auto;" />
```

But which does not render in the preview. Which is peculiar because it exists in this specified location. (I note that the missing logo in the README perhaps has to do with this as well) I wonder whether that result would be different in the online rendered version.

The `conductor` package example would suggest it would, because the site includes a gif and other images. However, those images are located inside an `articles/asset` subfolder, and not in the natural vignette subfolders (e.g., `articles/standardize_data_files/figure-gfm/unnamed-chunk-13-1.png`). Normally such subtle differences in path should not be an issue, but it is too early for me to tell.

**Comment by rempsyc** [comment]
The issue with images even seems to prevent the rendering of `use_docsify()` (or even `use_docute()`) for my own package, `rempsyc`:

```r
── Vignettes ───────────────────────────────────────────────────────────────────────────────────────────────────
ℹ Found 10 vignettes to convert.
[WARNING] Could not fetch resource ../docs/articles/assumptions_files/figure-gfm/unnamed-chunk-7-1.png
[WARNING] Could not fetch resource ../docs/articles/assumptions_files/figure-gfm/unnamed-chunk-10-1.png
Error: [ENOENT] Failed to remove 'C:/github/rempsyc/docs/articles/contrasts.Rmd': no such file or directory
✖ Converting vignettes: 3/10 [20s]
```

**Comment by rempsyc** [comment]
Using the current development version instead of this branch still has problems, but does not stop on error. We get instead this message:

```r
── Vignettes ───────────────────────────────────────────────────────────────────────────────────────────
ℹ Found 10 vignettes to convert.
✔ Converting vignettes: 10/10 [49s]

✔ The following vignettes have been converted and put in C:/github/rempsyc/docs/articles:
  • assumptions.Rmd
  • circles.Rmd
  • featured.Rmd
  • randomize.Rmd
  • scatter.Rmd
  • violin.Rmd

✖ The conversion failed for the following vignettes:
  • contrasts.Rmd
  • moderation.Rmd
  • t-test.Rmd
  • table.Rmd
```

Looking at the rendered websites, the vignettes that were successful successfully display, except once again for the images resulting from code (so this PR does not change this behaviour)

**Comment by rempsyc** [comment]
@vincentarelbundock what would you suggest focusing my efforts on here?

Options are:
1. Fix logo in README (new issue)
2. Fix rendering of vignette for `rempsyc` (not that I need it; still some vignettes failed before this PR)
3. Fix inclusion of code-generated images (old issue)
4. Fix functions not hyperlinked (old issue)
5. All (or a sub-selection) of those then merge, or
6. None of those, merge, and move to the next issue.

**Comment by vincentarelbundock** [comment]
> @vincentarelbundock what would you suggest focusing my efforts on here?

Sorry, that was a lot and I didn't quite follow everything. Which of those are **downgrades** relative to current functionality of the package?

Before merging, it would be ideal to fix the downgrades so we get back to feature-parity.

The other things should probably be listed as a checkbox list in a separate issue dedicated to collecting all the *improvements* (not downgrades) that we want to tackle. I can help prioritize that list.

**Comment by vincentarelbundock** [comment]
Sorry, I missed the parentheses. I guess you should just fix the "new issue" (README logo), and ask for code review.

It would also help me personally if you could give a list of commands --- without any commentary at all, just the code --- that I would need to execute if I wanted to convert a simple repository like `countrycode` or `WDI` to `docsify` or whichever framework is most mature in `altdoc` at the moment.

**Comment by etiennebacher** [comment]
@rempsyc here are some answers:

> (as a side note, I am not able to correctly install mkdocs on Windows 10, see: https://github.com/mkdocs/mkdocs/discussions/3427. Are you guys on Mac?)

I could use mkdocs without problem on Windows

> So the conclusion is that the name of the file defining the structure of the website differs based on the selected site builder.

Yes, exactly. This was a problem for adding vignettes directly into the website structure. For mkdocs and docsify, it's easy enough because it's a matter of inserting items into a list of bullet points, but for docute it looks like the only way is to edit the `index.html` file, which is not easy to do via R (maybe I missed something back then, but I don't think so). 

Therefore, since I wanted all formats to have the same functionalities, I decided to drop this automatic insertion of vignettes in the file that controls the website structure.

> In pkgdown, things like: `library(dplyr)` links externally to https://rdrr.io/r/base/library.html for library and https://dplyr.tidyverse.org/ for dplyr

I think this is minor but if you want to have a look at this, it is handled by `downlit` in the `pkgdown` process: https://github.com/r-lib/downlit/ 

---

@vincentarelbundock FYI I don't intend to work more on this PR, it was just a quick try at the time and I made a PR so that you guys have access to the code if you want to build on that. I'll close this and I suggest you move the discussion about vignettes to #43 (or split it in separate issues as you proposed) ;)

**Comment by vincentarelbundock** [comment]
Sounds great. @rempsyc just let me know if you have enough to go on right now, or if you need to chat.

**Pull request closed without merging**
