### PR TITLE
Implement snapshot tests

### LINKED ISSUE #221: Implement some sort of snapshot testing?
The main issue with testing is that the output of `render_docs()` is dozens or even hundreds of files. One way to test that changes don't break existing websites would be to take screenshots and compare them with the original.

Each time the test runs, it generates a fake package, renders the docs, then call `webshot2` to take a screenshot and compare it to the original. We can take several screenshots, for example to ensure that images are rendered in vignettes, or that we don't change by mistake the content of the "reference" page.

Potential problem: if the reference is generated on windows, will it make a difference to run the test on another OS?

@vincentarelbundock what do you think about this? did you run into some issues with `tinysnapshot` that could be problematic here?

### PR DESCRIPTION
**Pull request by etiennebacher**
Close #221 

This should prevent basic errors. 

Quarto files change depending on the version of quarto and we always get the latest one in CI, so I removed those snapshots for now. Also quarto files are quite big, at least 500 lines, even for very basic md source

### CODE REVIEW

**Comment by etiennebacher** [comment]
I had to disable the snapshots on Windows (only on CI so that I can still use them locally) because loading the library in the man pages generated an error (but only on windows??)

@vincentarelbundock do you want to try that locally see if that works fine for you?

**Comment by vincentarelbundock** [comment]
I'm on windows machine, but I have none of the dev tools installed and don't know how any of it works on this machine. (I'm always working in a Linux WSL). Is a windows test what you need, or do you just want me to run on any machine locally?

**Comment by etiennebacher** [comment]
It should work on any OS locally, just on ci there's this windows problem. Then as long as you have testthat installed it should run fine

**Comment by vincentarelbundock** [comment]
Cool. I don't get any error when I run `devtools::test()` in the `snapshot` branch on my local computer.

**Comment by etiennebacher** [comment]
Great, thanks for testing!

**Pull request merged**
