### PR TITLE
Link functions

### LINKED ISSUE #68: Function calls in vignettes could link to the man page
`pkgdown` does this.

Probably requires some regex magic.

### PR DESCRIPTION
**Pull request by etiennebacher**
Close #68

Maybe quarto does that for HTML docs (including quarto website) but not for markdown output. Need to pass via `downlit::downlit_md_path()` which takes a couple of seconds per file.

We lose the code block formatting, might be able to put it back by wrapping all `<pre>` in `<div class="pre-wrapper" data-lang="r">` in docute.

- [ ] fix formatting of code blocks
- [ ] check on other docs generators

### CODE REVIEW

**Comment by vincentarelbundock** [comment]
Do we really need this? `downlit` seems like a pretty big dependency and code complication for something that feels like a fringe feature...

Or maybe it should be optional?

**Comment by etiennebacher** [comment]
I think this is useful and it was also requested in `polars`. This can definitely be a post-processing script instead of a built-in thing, but we should "advertise" it or make it easy to discover by users

**Comment by eitsupi** [comment]
> Maybe quarto does that for HTML docs (including quarto website) but not for markdown output.

That's right. quarto-dev/quarto-cli#3777

**Comment by etiennebacher** [comment]
This probably wouldn't work for `mkdocs`. Basically `mkdocs build` does its own thing and generate their HTML file for each markdown file. Even if we could highlight everything in the md file, it would probably be removed by `mkdocs`.

I won't work on this any time soon so I'd rather close this

**Pull request closed without merging**
